### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [ramalone21/SQL-Training-Content#1]
### Criteria 1: Report
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ Overall good work presenting your query results and performing the analysis! For the last section, it'd be great if you could include some additional observations on the query results (ie. _What are some actionable insights for Warby Parker?_)
 
### Criteria 2: Query Accuracy
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ All queries accurately retrieve the data as intended - great job!
 
### Criteria 3: Query Formatting
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ Overall great job on the formatting! There are just a few places you could try to be more consistent in sticking with the recommended [style guide](https://s3.amazonaws.com/codecademy-content/programs/learn-sql-from-scratch/SQL+Style+Guide+for+Learn+SQL+from+Scratch.pdf), such as:
   - using uppercase for reserved keywords
   - using a separate line for each column in your `SELECT` clause
   - referring to columns by their col number in `GROUP BY` and `ORDER BY` clause

For example, this:
https://github.com/ramalone21/SQL-Training-Content/blob/d5ab537ed069108d8009ef3ea021fb5543fd4aeb/code.sql#L19-L22
could be written as:
```sql
SELECT style, 
    COUNT(*) AS responses
FROM quiz
GROUP BY 1 
ORDER BY 2 desc;
``` 
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Report demonstrates clear understanding​ of funnels.
 
### Overall Score: 14/16
Well done on this project! Your queries are also well-written and obtain the correct results. And overall great work presenting your findings! 
 
One additional thing you could do is incorporate calculating the percentages into your queries. For example, the query above can be further modified to:
```sql
SELECT style, 
    COUNT(*) AS responses,
    100.*COUNT(*)/(SELECT COUNT(*) FROM quiz) as 'response rate'
FROM quiz
GROUP BY 1 
ORDER BY 2 desc;
```
 
As a further challenge, continue exploring different SQL commands and test writing queries using this dataset. See if you are able to perform more analysis with this data. Have fun! :)

**Comment by ramalone21** [comment]
Thank you for the feedback! I had a lot of fun and learned a lot along the way!
